### ISSUE TITLE
would be nice if SvrfError conformed to the Error protocol

### ISSUE THREAD

**Issue by piemonte** [Svrf/svrf-ios-sdk#29]
# Feature request

would be nice if `SvrfError` conformed to the `Error` protocol

## Description

Any type that declares conformance to the Error protocol can be used to represent an error in Swift’s error handling system.

### "Why?"

If your app expects objects that conform to Error you don't need to create special handling for Svrf's error type.

### Possible solution

enum SvrfError: Error {
// ..
}

### Additional context

https://github.com/Alamofire/Alamofire/blob/1058f75b0c84aad8033727659fe898b09f05f49c/Source/AFError.swift

**Comment by brentchow** [comment]
We're planning for this to launch in a new major version release 2.0

**Comment by brentchow** [comment]
closed by #47. This will be released in a new major version release (2.0)
