### ISSUE TITLE
[Timebox] Allow iOS SDK user to cancel and manage outgoing requests

### ISSUE THREAD

**Issue by piemonte** [Svrf/svrf-ios-sdk#30]
# Feature request

## Description

if would be nice if outgoing request operations could be cancelled.

### "Why?"

if allows apps to proactively close open networking connection if a user navigates to another part of the app.

### Possible solution

one possibility is to provide a request object in return that can be cancelled. one could also provide an ID that could be passed into SvrfSDK to be cancelled too.

### Additional context

great SDK – nice work! ✌️

**Comment by brentchow** [comment]
We're planning for this to launch in a new major version release 2.0
