### ISSUE TITLE
SDK no longer compiles (internal dependency automatically updated)

### ISSUE THREAD

**Issue by piemonte** [Svrf/svrf-ios-sdk#33]
# Bug report

## Describe the bug

The current SDK release automatically picked up a newer version of it's internal client:

-  - SVRFClient (1.3.2):
+  - SVRFClient (1.4.0):

The problem is that this causes compilation issues for 1.0.3:

/Pods/SvrfSDK/SvrfSDK/Source/SvrfSDK.swift:137:73: Cannot convert value of type 'String?' to expected argument type 'MediaAPI.StereoscopicType_search?'
/Pods/SvrfSDK/SvrfSDK/Source/SvrfSDK.swift:178:33: Incorrect argument label in call (have 'type:stereoscopicType:category:size:nextPageCursor:completion:', expected 'type:stereoscopicType:category:size:minimumWidth:completion:')
### Desktop

- OS: 
- Browser: 
- Version: 

### Mobile

- Device: 
- OS: 
- Browser: 
- Version:

**Comment by brentchow** [comment]
Hey @piemonte, Thanks for reporting this! We'll be releasing a patch that pins dependencies ASAP. cc: @AndreiEvstratenko

**Comment by piemonte** [comment]
no problem – thanks for the fast fix! ✌️

**Comment by brentchow** [comment]
@piemonte we just published a patch (1.0.4).

PS Early next week we'll be bumping a minor version with fixed pagination :)
