### ISSUE TITLE
[Timebox] Support Swift 5

### ISSUE THREAD

**Issue by piemonte** [Svrf/svrf-ios-sdk#38]
# Feature request

## Description

With the latest release of Xcode 10.2 (10E125), Swift 5 is now available, would be nice to have support for it.

**Comment by brentchow** [comment]
We're planning for this to launch in a new major version release 2.0

**Comment by brentchow** [comment]
@AndreiEvstratenko will investigate if there will be any issues with the dependencies but doesn't think it'll take a lot of time.

**Comment by AndreiEvstratenko** [comment]
@ox @jexe @brentchow Hey, guys! See the description of the pull request. https://github.com/Svrf/svrf-ios-sdk/pull/61
