### ISSUE TITLE
update to use SVRFClient 1.6

### ISSUE THREAD

**Issue by piemonte** [Svrf/svrf-ios-sdk#40]
# Bug report

## Describe the bug

Hey SVRF, apologies for the additional issue about the recent Xcode update.

I'm using both this library and your SVRFClient, so I'm kinda stuck from using the API until I can clear this Xcode issue.

It'd be nice if this library could also be updated to use the fixes in the SVRFClient. 

📎 https://github.com/Svrf/svrf-swift4-client/issues/4

**Comment by brentchow** [comment]
This should be resolved in this morning’s release of [1.1.0](https://github.com/Svrf/svrf-ios-sdk/releases/tag/1.1.0)
